<a href="https://colab.research.google.com/github/Diegoarmando24/Practica-2/blob/main/Ejercicio25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Factorización de *Cholesky*

In [71]:
import numpy as np

In [67]:
# (b) A = LDL^t , donde L es triangular inferior y D es diagonal.

# Función que realiza la factorización LU de una matriz A
# Devuelve L (triangular inferior con unos en la diagonal) y U (triangular superior)
def LU(A):
  U = np.copy(A)             # Copiamos A para no modificar la original
  L = np.eye(A.shape[0])     # Inicializamos L como matriz identidad

  for i in range(A.shape[0]):
    Li = np.eye(A.shape[0])  # Matriz elemental de eliminación
    for j in range(i+1, A.shape[0]):
      Li[j, i] = -U[j, i] / U[i, i]  # Pivoteo para anular elemento debajo del pivote
      L[j, i] = U[j, i] / U[i, i]    # Se guarda el multiplicador en L
    U = MultMat(Li, U)       # Se aplica la eliminación gaussiana
  return L, U                # Retorna las matrices L y U

# Función que extrae la parte diagonal de una matriz (el resto se pone en cero)
def Diag(mat):
  for i in range(mat.shape[0]):
    for j in range(mat.shape[1]):
      if i != j:
        mat[i, j] = 0        # Se eliminan los elementos fuera de la diagonal
  return mat                 # Se devuelve la matriz diagonal

# Función que calcula la transpuesta de una matriz de forma manual (sin np.T)
def Transpuesta(matriz):
    copia = np.copy(matriz) # Se trabaja con una copia para no modificar la original
    for ren in range(copia.shape[0]):
        for col in range(copia.shape[1]):
            if ren < col:
                # Intercambia simétricamente para obtener la transpuesta
                copia[ren, col], copia[col, ren] = copia[col, ren], copia[ren, col]
    return copia

# Función que implementa la factorización de Cholesky en forma A = LDL^t
def FactorizacionCholeskyB(matriz):
    L, U = LU(np.copy(matriz)) # Se obtiene la factorización LU
    D = Diag(U)                # Extraemos la matriz diagonal de U
    LTrans = Transpuesta(L)   # Obtenemos la transpuesta de L
    return L, D, LTrans       # Retornamos L, D y L^t

In [68]:

# Matriz de prueba (simétrica y definida positiva)
matriz = np.array([[4.0, 2.0, 2.0],
                   [2.0, 10.0, 4.0],
                   [2.0, 4.0, 6.0]])

# Se imprime la descomposición A = LDL^t
print("La matriz L es:\n", FactorizacionCholeskyB(matriz)[0])
print("La matriz D es:\n", FactorizacionCholeskyB(matriz)[1])
print("La matriz L^t es:\n", FactorizacionCholeskyB(matriz)[2])
print("La multiplicación LDL^t es:\n", FactorizacionCholeskyB(matriz)[0] @ FactorizacionCholeskyB(matriz)[1] @ FactorizacionCholeskyB(matriz)[2], " = A")


La matriz L es:
 [[1.         0.         0.        ]
 [0.5        1.         0.        ]
 [0.5        0.33333333 1.        ]]
La matriz D es:
 [[4. 0. 0.]
 [0. 9. 0.]
 [0. 0. 4.]]
La matriz L^t es:
 [[1.         0.5        0.5       ]
 [0.         1.         0.33333333]
 [0.         0.         1.        ]]
La multiplicación LDL^t es:
 [[ 4.  2.  2.]
 [ 2. 10.  4.]
 [ 2.  4.  6.]]  = A


In [69]:

# (a) A = LL^t, usando L * D^(1/2) * D^(1/2) * L^t

# Función que multiplica dos matrices manualmente (sin usar np.dot o el operador @)
def MultMat(Mat1, Mat2):
    Mat3 = np.zeros((Mat1.shape[0], Mat2.shape[1]))  # Inicializa la matriz resultado

    for row in range(Mat1.shape[0]):
        for col in range(Mat2.shape[1]):
            for aux in range(Mat2.shape[0]):
                Mat3[row, col] += Mat1[row, aux] * Mat2[aux, col]  # Producto punto
    return Mat3

# Función que convierte la factorización A = LDL^t a A = LL^t
# usando L * D^(1/2) y D^(1/2) * L^t
def FactorizacionCholeskyA(matriz):
    L, D, Ltrans = FactorizacionCholeskyB(np.copy(matriz))  # Se obtiene LDL^t

    # Se saca raíz cuadrada a los elementos de la diagonal de D
    for i in range(D.shape[0]):
        D[i, i] = np.sqrt(D[i, i])

    # Se forman L' = L D^(1/2) y L'^t = D^(1/2) L^t
    LPrim = MultMat(L, D)
    LPrimT = MultMat(D, Ltrans)

    return LPrim, LPrimT     # Retorna L' y L'^t


In [70]:

# Matriz de prueba (igual que antes)
matriz = np.array([[4.0, 2.0, 2.0],
                   [2.0, 10.0, 4.0],
                   [2.0, 4.0, 6.0]])

# Se imprime la descomposición A = LL^t
print("La matriz L' es:\n", FactorizacionCholeskyA(matriz)[0])
print("La matriz L'^t es:\n", FactorizacionCholeskyA(matriz)[1])
print("La multiplicación LL^t es:\n", FactorizacionCholeskyA(matriz)[0] @ FactorizacionCholeskyA(matriz)[1], " = A")


La matriz L' es:
 [[2. 0. 0.]
 [1. 3. 0.]
 [1. 1. 2.]]
La matriz L'^t es:
 [[2. 1. 1.]
 [0. 3. 1.]
 [0. 0. 2.]]
La multiplicación LL^t es:
 [[ 4.  2.  2.]
 [ 2. 10.  4.]
 [ 2.  4.  6.]]  = A
