<a href="https://colab.research.google.com/github/Diegoarmando24/Practica-2/blob/main/Ejercicio_25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Ejercicio 25 - Factorización de Cholesky clásica y modificada
import numpy as np

# ==========================================
# FACTORIZACIÓN DE CHOLESKY CLÁSICA
# ==========================================

def Cholesky(A):
    """
    Realiza la factorización de Cholesky clásica: A = L · Lᵗ
    donde A es una matriz simétrica definida positiva.

    Retorna:
        L : matriz triangular inferior tal que A = LLᵗ
    """
    n = A.shape[0]
    L = np.zeros_like(A)

    for i in range(n):
        for j in range(i + 1):
            suma = 0.0
            # Suma acumulada de productos L[i][k] * L[j][k] hasta k = j - 1
            for k in range(j):
                suma += L[i][k] * L[j][k]

            if i == j:
                # Diagonal: sqrt(a_ii - sumatorio)
                L[i][j] = (A[i][i] - suma) ** 0.5
            else:
                # Fuera de la diagonal
                L[i][j] = (A[i][j] - suma) / L[j][j]

    return L

# ==========================================
# FACTORIZACIÓN DE CHOLESKY MODIFICADA
# ==========================================

def Cholesky_Modificada(A):
    """
    Realiza la factorización de Cholesky modificada: A = L̂ · D̂ · L̂ᵗ

    Donde:
        L̂ : matriz triangular inferior con 1's en la diagonal
        D̂ : matriz diagonal

    Retorna:
        L_hat : matriz L̂
        D_mat : matriz diagonal D̂
    """
    n = A.shape[0]
    L_hat = np.zeros_like(A)
    D_hat = np.zeros(n)

    for i in range(n):
        for j in range(i):
            suma = 0.0
            # Suma acumulada de productos L̂[i][k] * D̂[k] * L̂[j][k]
            for k in range(j):
                suma += L_hat[i][k] * D_hat[k] * L_hat[j][k]
            L_hat[i][j] = (A[i][j] - suma) / D_hat[j]

        # Cálculo del valor diagonal D̂[i]
        suma = 0.0
        for k in range(i):
            suma += (L_hat[i][k] ** 2) * D_hat[k]
        D_hat[i] = A[i][i] - suma

        # Por construcción, la diagonal de L̂ es 1
        L_hat[i][i] = 1.0

    D_mat = np.diag(D_hat)  # Se convierte el vector D̂ en matriz diagonal
    return L_hat, D_mat

# ==========================================
# PRUEBA CON MATRIZ A
# ==========================================

# Matriz simétrica definida positiva
A = np.array([[4.0, 2.0],
              [2.0, 3.0]])

# ----------------- Cholesky clásica -----------------
L = Cholesky(A)
print("L (Cholesky clásica):\n", L)
print("Reconstrucción A (LL^T):\n", L @ L.T)

# ----------------- Cholesky modificada -----------------
Lh, Dh = Cholesky_Modificada(A)
print("\nL_gorrito (modificada):\n", Lh)
print("D_gorrito (diagonal):\n", Dh)
print("Reconstrucción A (L_gorrito * D_gorrito * L_gorrito^T):\n", Lh @ Dh @ Lh.T)



L (Cholesky clásica):
 [[2.         0.        ]
 [1.         1.41421356]]
Reconstrucción A (LL^T):
 [[4. 2.]
 [2. 3.]]

L_gorrito (modificada):
 [[1.  0. ]
 [0.5 1. ]]
D_gorrito (diagonal):
 [[4. 0.]
 [0. 2.]]
Reconstrucción A (L_gorrito * D_gorrito * L_gorrito^T):
 [[4. 2.]
 [2. 3.]]
